0-transfer_file

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,14 +1,28 @@
 #!/usr/bin/env bash
 # bash: script transfers a file from the client to a server using scp
 
-if [ $# -lt 4 ]; then
-    echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
-    exit 1
+if [ $# -lt 4 ]
+then
+	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+	exit 1
 fi
+
+# assigning parameters to variables
 
 file_path=$1
 server_ip=$2
 username=$3
 ssh_auth_key=$4
 
-scp -o StrictHostKeyChecking=no -i "$ssh_auth_key" "$file_path" "$username@$server_ip:~/"
+#dasabling strict host key
+
+scp -o "StrictHostKeyChecking=no" -i "$ssh_auth_key" "$file_path" "$username@$server_ip:~/"
+
+# checking if the transfer was successful
+
+if [ $? -eq 0 ]
+then
+	echo "FILE WAS TRANSFERED SUCCESSFULLY"
+else
+	echo "FILE TRANSFER FAILED"
+fi
